# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
language: python
matrix:
  include:
  ##
  ## Test with conda-forge sagemath package
  ##
  - env: CACHE_NAME=conda CONDA_ENV=sage-cgf DEPLOY_DOC_TO_DIRECTORY=doc/html
    python: "2.7"    ## just for display. The version used is actually determined by conda.
    before_install:
    - source ./.travis-install.sh
    - conda env create -n $CONDA_ENV -f environment-python2.yml || conda env update -n $CONDA_ENV --prune -f environment-python2.yml
    - conda activate $CONDA_ENV
  - env: CACHE_NAME=conda-py3 CONDA_ENV=sage-cgf-py3
    python: "3.7"    ## just for display. The version used is actually determined by conda.
    before_install:
    - source ./.travis-install.sh
    - conda env create -n $CONDA_ENV -f environment.yml || conda env update -n $CONDA_ENV --prune -f environment.yml
    - conda activate $CONDA_ENV
  - env: CACHE_NAME=conda-py3-latestsage CONDA_ENV=sage-cgf-latestsage
    python: "3.7"    ## just for display. The version used is actually determined by conda.
    before_install:
    - source ./.travis-install.sh
    - conda env create -n $CONDA_ENV -f environment-latestsage.yml || conda env update -n $CONDA_ENV --prune -f environment-latestsage.yml
    - conda activate $CONDA_ENV
install:
- ./.travis-install.sh
script:
- ./.travis-test.sh
cache:
  directories:
  - "$HOME/miniconda"
  - "$HOME/SageMath"
  - "$HOME/.cache/matplotlib"
  timeout: 1000
before_cache:
- rm -Rf $HOME/SageMath/logs $HOME/SageMath/.BUILDSTART
#after_success:
#- ./.travis-deploy-doc.sh
before_script:
- openssl aes-256-cbc -K $encrypted_f96cc3b3888c_key -iv $encrypted_f96cc3b3888c_iv
  -in .travis_ci_gh_pages_deploy_key.enc -out .travis_ci_gh_pages_deploy_key -d || true

addons:
  apt:
    packages:
     # On 8.0 with trusty, Fortran compiler is needed.
     # Otherwise, numpy cannot be imported.
     # Also, optional package installs in .travis-install.sh will trigger build of sage gcc.
     - gfortran
